export const textSimilarityInstruction = `You are to compare two citations. First one is Gold citation, 
  meaning your source of truth. The second one is generated by LLM. 
  Your task is to evaluate if the second citation is correct. 
  In response a js object: {
    score: 0 - 1,
    reasoning: reasoning
  }`;
